### ISSUE TITLE
Long term module plans

### ISSUE THREAD

**Issue by vlahan** [mholt/caddy-grpc-web#7]
Hi @mholt,

First of all I want to thank you for your work on caddy-server and also for this module!

Despite the experimental nature, we are using the module successfully in our projects and would appreciate if you can share your thoughts on its long-term maintenance prospects.

Are there  plans to integrate this as standard module in caddy-server and to address some of the issues listed in https://github.com/mholt/caddy-grpc-web/blob/2deb9fd4ddd703e0037e63edb5bcd7a4df85f66f/grpcweb.go#L37 ?

**Comment by mholt** [comment]
Hey @vlahan -- good question.

These days, for a module to be included in our standard distribution, it has to be generally applicable and relatively popular. Right now I'm not sure how many users are bridging gRPC-Web (thanks to lack of telemetry, which the community voted against years ago, despite my better judgment, sigh). So all I have to go on is feedback like yours, which I appreciate.

I'm really glad to hear you're using it successfully!

As for long-term plans, I don't personally use this module myself, so it basically comes down to low maintenance tasks to keep it functional, things like updating dependencies or reviewing pull requests; but at the current usage level I don't foresee myself investing much time into it, since it works as-is.

That said, I'm always able to help our [sponsors](https://github.com/sponsors/mholt) with whatever they need. In this case, this module simply wraps another library which I don't have control over. If the sponsorship tier is sufficient, we can fork and maintain dependencies if needed, implement optimizations, etc. I also maintain dev branches for some sponsors, like Stripe, who have specific dependency and patch requirements.

So yeah, I'd be happy to address those points with this library. Can we get you set up on a sponsorship? Higher tiers offer significant discounts for dev work (and for some it's free -- for example, for the work I do for Stripe is included in their sponsorship).

**Comment by vlahan** [comment]
Hi @mholt, thanks a lot for taking the time for a comprehensive feedback!

I am glad to hear that the basic maintenance to keep the module in step with the caddy-server releases is not endangered despite its experimental nature.  I don't have a good grasp on the size of the overall grpc-web community. I assume many in the cloud / API servers domain gravitate to envoy for grpc-web out of inertia. Our use is a bit specific as we deploy it on an embedded device as part of the configuration and telemetry system. In this context caddy has clear benefits, both for efficiency and portability reasons, but at the same time the size of the market is definitely smaller.

Thanks for pointing the benefits of the different sponsorship tiers, we will take a look and would be glad to support within our means as a small company.

**Comment by mholt** [comment]
Yeah this module is sticking around, I just consider it "done" for now -- (it's not "done" as we discussed but until it is funded I'm basically done with it).
